---
title: "Make a hex sticker for the SLC RUG!"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, dpi = 600)
```

## Get some population data for Utah

```{r utah}
library(tidyverse)
library(tidycensus)
library(sf)

options(tigris_use_cache = TRUE)

utah_raw <- get_acs(state = "UT", 
                    geography = "tract", 
                    variables = "B01003_001",  
                    geometry = TRUE)

area <- utah_raw %>% 
    select(geometry) %>% 
    st_area() %>%
    as.numeric()

utah <- bind_cols(utah_raw, data_frame(area = area))

head(utah)
```



```{r}
library(viridis)
library(hexSticker)

ut <- utah %>%
    ggplot(aes(fill = log2((estimate + 25) / area), 
               color = log2((estimate + 25) / area))) + 
    geom_sf() + 
    scale_fill_viridis(begin=.3, end=.9) + 
    scale_color_viridis(begin=.3, end=.9) + 
    theme_minimal() +
    theme(legend.position="none") +
    theme(axis.text.x=element_blank(),
          axis.text.y=element_blank(),
          panel.grid.major = element_line(colour = "transparent")) +
    theme_transparent()

ut

sysfonts::font_add_google("Baloo Tammudu", "baloo")

sticker(ut,
        package = "slc rug", 
        p_size = 12.5,
        p_y = 1,
        p_family = "baloo",
        p_color = "#ffffff",
        h_fill = "#453781FF",
        h_color = "#ffffff",
        h_size = 2,
        s_x = 1, s_y = 1, 
        s_width = 1.6, s_height = 1.6,
        url = "github.com/slc-rug",
        u_color	= "#ffffff",
        u_size = 1.2,
        filename="slcrug_hex.png")

```


